services:
    # event listener
    tenolo_twig_extensions.twig_config.number_format:
        class: Tenolo\Bundle\TwigExtensionsBundle\EventListener\TwigConfigNumberFormatListener
        arguments: ['@twig']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # twig extensions
    tenolo_twig_extensions.twig_extension.filesize:
        class: Tenolo\Twig\Extensions\Extension\FilesizeExtension
        tags:
            - { name: twig.extension }

    tenolo_twig_extensions.twig_extension.array:
        class: Tenolo\Twig\Extensions\Extension\ArrayExtension
        tags:
            - { name: twig.extension }

    tenolo_twig_extensions.twig_extension.color:
        class: Tenolo\Twig\Extensions\Extension\ColorExtension
        tags:
            - { name: twig.extension }

    tenolo_twig_extensions.twig_extension.content:
        class: Tenolo\Twig\Extensions\Extension\ContentExtension
        tags:
            - { name: twig.extension }

    # external twig extensions
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    tenolo_twig_extensions.twig_extension.deferred:
        class: Phive\Twig\Extensions\Deferred\DeferredExtension
        tags:
            - { name: twig.extension }

    # symfony bridge
    tenolo_twig_extensions.twig_extension.container:
        class: Tenolo\Bundle\TwigExtensionsBundle\Twig\Extension\ContainerExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }

    tenolo_twig_extensions.twig_extension.form:
        class: Tenolo\Bundle\TwigExtensionsBundle\Twig\Extension\FormExtension
        arguments: ['@translator']
        tags:
            - { name: twig.extension }

    tenolo_twig_extensions.twig_extension.routing:
        class: Tenolo\Bundle\TwigExtensionsBundle\Twig\Extension\RoutingExtension
        arguments:
            - '@router'
            - '@request_stack'
        tags:
            - { name: twig.extension }
