services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # service
    Tenolo\Bundle\TwigExtensionsBundle\Service\TwigGlobalsManager: ~
    tenolo_twig_extensions.twig_globals: '@Tenolo\Bundle\TwigExtensionsBundle\Service\TwigGlobalsManager'

    # event listener
    Tenolo\Bundle\TwigExtensionsBundle\EventListener\TwigConfigNumberFormatListener: ~

    # twig extensions
    Tenolo\Twig\Extensions\Extension\FilesizeExtension: ~
    Tenolo\Twig\Extensions\Extension\ArrayExtension: ~
    Tenolo\Twig\Extensions\Extension\ColorExtension: ~
    Tenolo\Twig\Extensions\Extension\ContentExtension: ~

    # external twig extensions
    Twig\Extensions\TextExtension: ~
    Phive\Twig\Extensions\Deferred\DeferredExtension: ~

    # symfony bridge
    Tenolo\Bundle\TwigExtensionsBundle\Twig\Extension\ContainerExtension:
        arguments: ['@service_container']

    Tenolo\Bundle\TwigExtensionsBundle\Twig\Extension\FormExtension: ~
    Tenolo\Bundle\TwigExtensionsBundle\Twig\Extension\RoutingExtension: ~
    Tenolo\Bundle\TwigExtensionsBundle\Twig\Extension\TwigGlobalsExtension: ~
