services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # service
    Tenolo\Bundle\TwigExtensionsBundle\Service\:
        resource: '../../Service/*'

    # event listener
    Tenolo\Bundle\TwigExtensionsBundle\EventListener\:
        resource: '../../EventListener/*'

    # twig extensions
    Tenolo\Twig\Extensions\Extension\ArrayExtension: ~
    Tenolo\Twig\Extensions\Extension\ColorExtension: ~
    Tenolo\Twig\Extensions\Extension\ContentExtension: ~
    Tenolo\Twig\Extensions\Extension\FilesizeExtension: ~

    # external twig extensions
    Twig\Extensions\TextExtension: ~
    Phive\Twig\Extensions\Deferred\DeferredExtension: ~

    # symfony bridge
    Tenolo\Bundle\TwigExtensionsBundle\Twig\Extension\ContainerExtension:
        arguments: ['@service_container']

    Tenolo\Bundle\TwigExtensionsBundle\Twig\Extension\:
        resource: '../../Twig/Extension/*'

    # legacy
    tenolo_twig_extensions.twig_globals:
        alias: Tenolo\Bundle\TwigExtensionsBundle\Service\TwigGlobalsManager
        public: true
